### PR TITLE
Track configuration in local git repositories

### PR DESCRIPTION
**Pull request by djmitche**
Fixes #3162.

### CODE REVIEW

**Comment by verm** [comment]
Looks awesome.  Shell script, too!

**Comment by sa2ajj** [comment]
I'd consider using pre-tasks, post-tasks

**Comment by sa2ajj** [comment]
Check out http://docs.ansible.com/playbooks_roles.html#roles for pre_tasks, post_tasks

**Comment by djmitche** [comment]
It looks like those are only for running *within* a playbook, before and after the roles in that playbook.  But `local.yml` is a sequence of playbooks.  Is there a way to make that work?

**Comment by sa2ajj** [comment]
Yes, you are right.  Let's proceed with this version and see how it can be improved later.

**Comment by sa2ajj** [comment]
It depends on the host being fully configured (e.g. sudo stuff):

```
TASK: [install track-config.sh] *********************************************** 
failed: [localhost] => {"failed": true, "parsed": false}
invalid output was: 
We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo via ansible, key=refyqwtucmwouaugtiirlaofhrmgnfex] password: 


FATAL: all hosts have already failed -- aborting
```

**Pull request merged**
