### PR TITLE
Add TLS support to proxied sites

### PR DESCRIPTION
**Pull request by seankelly**
The one part that was missing still for TLS were the proxied Buildbot instances. I moved the TLS configuration to a separate file so the static and proxy configurations won't drift.

### CODE REVIEW

**Comment by sa2ajj** [comment]
:+1:

**Comment by djmitche** [comment]
:+1: here too -- deploy when you're around to back out any failures.

**Comment by sa2ajj** [comment]
and let's watch those failures :)

**Comment by djmitche** [comment]
fix in be670b32e0d502759c4c4b29413586431ea73df4

**Pull request merged**
