### PR TITLE
Bug 3245: make www.buildbot.net an A record instead of CNAME

### PR DESCRIPTION
**Pull request by djmitche**

### CODE REVIEW

**Comment by seankelly** [comment]
Not sure if this will help though. `www.buildbot.net` resolves to .238 and that reverse resolves to `buildbot.net`.

**Comment by djmitche** [comment]
Good point.  Also, I didn't increment the serials.  How's this?

**Comment by seankelly** [comment]
Looks good.

**Comment by seankelly** [comment]
I wonder if there's a way to have the serial set automatically with Ansible. The `ansible_managed` variable includes that information but it also includes a lot of other things.

**Comment by seankelly** [comment]
Checking the Ansible source, there's a `template_mtime` variable that isn't in the docs. That returns a datetime object containing the modified time of the template. I think a `{{ template_mtime..strftime('%Y%m%d%H%M%S') }}` would do it then. I'll experiment a bit and open a PR if it works and there's any interest in that.

**Comment by djmitche** [comment]
Sounds good -- I forget every time!

**Pull request merged**
